config/routes.rb
Rails.application.routes.draw do
  resources :investors
  resources :trades

  root 'korakot#report'

  get 'korakot/:action' => 'korakot'

end

app/models/investor.rb
class Investor
  include Mongoid::Document
  field :name_en, type: String
  field :name_th, type: String
end

app/models/trade.rb
class Trade

  include Mongoid::Document

  field :trade_on, type: Date
  field :ins_buy, type: Float
  field :ins_sell, type: Float
  field :fin_buy, type: Float
  field :fin_sell, type: Float
  field :for_buy, type: Float
  field :for_sell, type: Float
  field :ret_buy, type: Float
  field :ret_sell, type: Float
  field :set_index, type: Float
  field :created_at, type: Time

  def self.test_string
    self.new.string2f('1,234')
  end
  def self.get_data
    require 'open-uri'
    url = "http://marketdata.set.or.th/mkt/investortype.do?language=th&country=TH"
    doc = Nokogiri::HTML(open(url).read)
    num = []
    tran_date = doc.css('strong')[1].text
    tran_on = tran_date[/[0-9]+.+[0-9]+/]
    data = doc.at_css('.background')
    data.css('td[align="right"]').each do |v|
      vs = v.text[/[\-0-9,\.]+/]
      num << self.new.string2f(vs)
    end
    url = "http://marketdata.set.or.th/mkt/marketsummary.do?language=th&country=TH"
    doc = Nokogiri::HTML(open(url).read)
    set_index = self.new.string2f(doc.css('tr:nth-child(8) td')[1].text)
    trade = Trade.create :trade_on=> self.new.date_thai2date(tran_on),
      :ins_buy => num[0], :ins_sell => num[2],
      :fin_buy => num[6], :fin_sell => num[8],
      :for_buy => num[12], :for_sell => num[14],
      :ret_buy => num[18], :ret_sell => num[20],
      :set_index => set_index, :created_at => Time.now
  end

  # private
  def string2f(s)
    s.gsub(',','').to_f
  end
  def date_thai2date(s)
    # s in format 17 ก.ย. 2557
    mh = {'ม.ค.'=>1, 'ก.พ.'=>2, 'มี.ค.'=>3, 'เม.ย.'=>4, 'พ.ค.'=>5, 'มิ.ย.'=>6,
      'ก.ค.'=>7, 'ส.ค.'=>8, 'ก.ย.'=>9, 'ต.ค.'=>10, 'พ.ย.'=>11, 'ธ.ค.'=>12}
    ss= s.split(' ')
    month = mh[ss[1]]
    year = ss[2].to_i-543
    Date.new(year,month,ss[0].to_i)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show, :edit, :update, :destroy]

  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1
  # PATCH/PUT /investors/1.json
  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to investors_url, notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investor_params
      params.require(:investor).permit(:name_en, :name_th)
    end
end

app/controllers/korakot_controller.rb
class KorakotController < ApplicationController
  def report
    @trades = Trade.all.desc(:created_at)
  end
  def get_data
    trade = Trade.get_data
    # render :json=> trade.to_yaml
    redirect_to action: 'report'
  end

  # use for testing - get html from web and save to local file
  # to test Nokogiri parsing
  def get_index
    # url = "http://marketdata.set.or.th/mkt/marketsummary.do?language=th&country=TH"
    # file = File.open('tmp/sample_index.html','w') do |f|
    #   f.binmode
    #   f << open(url).read
    # end
    file_name= 'tmp/sample_index.html'
    f = File.read(file_name)
    doc = Nokogiri::HTML(f)
    set_index = doc.css('tr:nth-child(8) td')[1].text
    render :text => string2f(set_index)
  end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/korakot_helper.rb
module KorakotHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/investors/_form.html.erb
<%= form_for(@investor) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_en %><br>
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :name_th %><br>
    <%= f.text_field :name_th %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing investor</h1>

<%= render 'form' %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<h1>Listing investors</h1>

<table>
  <thead>
    <tr>
      <th>Name en</th>
      <th>Name th</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.name_en %></td>
        <td><%= investor.name_th %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investor', new_investor_path %>

app/views/investors/new.html.erb
<h1>New investor</h1>

<%= render 'form' %>

<%= link_to 'Back', investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name en:</strong>
  <%= @investor.name_en %>
</p>

<p>
  <strong>Name th:</strong>
  <%= @investor.name_th %>
</p>

<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>

app/views/korakot/report.html.erb
<table style='width:80%; margin: auto;'>
  <tr>
    <th>&nbsp;</th>
    <th>Date</th>
    <th>Ins Buy</th>
    <th>Ins Sell</th>
    <th>Fin Buy</th>
    <th>Fin Sell</th>
    <th>For Buy</th>
    <th>For Sell</th>
    <th>Ret Buy</th>
    <th>Ret Sell</th>
    <th>SET</th>
    <th>Volume</th>
    <th>Created</th>
  </tr>
  <% @trades.each do |trade| %>
    <tr>
      <td><%= link_to image_tag('cross.png'), trade, :data=> {confirm: "Are you sure?"}, :method=> :delete %></td>
      <td><%= trade.trade_on %></td>
      <td class='num'><%= trade.ins_buy %></td>
      <td class='num'><%= trade.ins_sell %></td>
      <td class='num'><%= trade.fin_buy %></td>
      <td class='num'><%= trade.fin_sell %></td>
      <td class='num'><%= trade.for_buy %></td>
      <td class='num'><%= trade.for_sell %></td>
      <td class='num'><%= trade.ret_buy %></td>
      <td class='num'><%= trade.ret_sell %></td>
      <td class='num'><%= trade.set_index %></td>
      <% vol = trade.ins_buy+trade.fin_buy+trade.for_buy+trade.ret_buy %>
      <td class='num'><%= number_with_precision(vol,precision:2, delimiter:',') %></td>
      <td class='num'><%= trade.created_at.strftime('%c') %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Get Data', action:'get_data' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Remora Www" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Remora Www" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>